### ISSUE TITLE
galaxy-central repository on bitbucket should probably not be used in readme

### ISSUE THREAD

**Issue by martenson** [fredhutchio/argo-navis#2]
The Galaxy project development moved to Github (https://github.com/galaxyproject/galaxy) so if you want to check out the latest you should check out that repository's `#dev` branch.

Alternatively if you want the latest stable/distribution you can use the `#master` branch.

The former distribution repo at https://bitbucket.org/galaxy/galaxy-dist is and will be supported.

**Comment by bcclaywell** [comment]
Thanks, Martin.
